version: '2'
services:
  server:
    command: 'make start-server-dev'
    environment:
      - 'DBHOST=rethinkdb'
    volumes:
      - '.:/code'
      - '/code/node_modules'
    image: 'docker-chat.dev-server'
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
    links:
      - 'rethinkdb'
    ports:
      - '8082:8082'

  rethinkdb:
    volumes:
      - '${PWD}/dbdata:/data'
    image: 'rethinkdb'
    ports:
      - '8081:8080'
      - '28015:28015'

  builder:
    command: 'make run-dev-client'
    environment:
      - 'DOCKER_DEV=true'
    volumes:
      - '.:/code'
      - '/code/node_modules'
    image: 'docker-chat.dev-webpack'
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
    links:
      - 'server'
    ports:
      - '8080:8080'
